# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the entire project folder contents into the container
COPY .. /app

# Copy the README.md into the container
COPY README.md /app/README.md

# Install dependencies
RUN pip install --no-cache-dir -r config/requirements.txt

# Expose the port Flask will run on
EXPOSE 5000

# Set environment variables to run Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run the Flask application
CMD ["flask", "run"]
